/*
The program generates a random integer in the interval 1-10
(including both 1 and 10).

The user runs the program guessing what the computer generates
using the command line argument.

If the user guessed the number generated by the program
the program outputs "Well done!"

Otherwise the program outputs: "Play once more!"
meaning that the user can run the program once more

*/

public class E2{

  public static void main(String[] args) {
    int programGuess = 0;
    int userSays = Integer.parseInt(args[0]);
    String message = "I don't know";

    programGuess = (int) (Math.random() * 10) + 1;
    if (userSays == programGuess)
    System.out.println("The random chosen number is: " + programGuess + " And you won!");
    else
    System.out.println("The random chosen number was: " + programGuess + " Try playing once more");


  }

}
